### ISSUE TITLE
Blade description

### ISSUE THREAD

**Issue by mpomarlan** [ease-crc/ease_ontology#18]
Currently, the description of DesignedBlade is

<rdfs:comment>An item designed to cut things.</rdfs:comment>

It used to be (and in the ELAN branch still is)

<rdfs:comment>An item designed to provide at least one sharp edge.</rdfs:comment>

which I think is preferable. The characteristic of the blade is that it has at least one sharp edge. It is true that basically all blades are used for cutting-- I say basically all out of charity, I can't think of a blade not meant to cut-- however, imo, it is not true that all items designed for cutting are, or have, blades.  A counterexample is a laser or waterjet cutter, and a cheese-cutting string would not be considered a blade either.

**Comment by daniel86** [comment]
sorry, that's my fault.

my reasoning was that the design is not about a sharpness, but rather about the use of it as tool for a certain action. Because it is not sufficient for being a designed blade to have a sharp edge, but it is rather the purpose to cut into something.

**Comment by daniel86** [comment]
What about combining it:
"An item designed to provide at least one sharp edge to be used for cutting into other objects"

**Comment by mpomarlan** [comment]
That sounds good.

**Comment by daniel86** [comment]
I'll take the freedom to push that change into master without review :)
