### ISSUE TITLE
results of ontology evaluation with OOPS!

### ISSUE THREAD

**Issue by mcodescu** [ease-crc/ease_ontology#21]
I have tested the ontologies with the evaluation tool OOPS! (http://oops.linkeddata.es), that detects common problems in the ontologies. For the modules, there was virtually no problem reported. For the EASE ontology (https://raw.githubusercontent.com/ease-crc/ease_ontology/master/owl/EASE.owl in the `Scanner by URI`), the tool made however a number of suggestions, e.g. missing domain and range axioms, or using recursive definitions. The tool does not provide a txt export from the web results, so you would have to run the check again (does not take long) to have a look at them and consider whether their suggestions should be followed or not.

**Comment by mpomarlan** [comment]
I've saved the html of the results, so anyone interested can download them and have a look:

https://drive.google.com/file/d/1T3k_6zR2n6Bvp3KrBqHYePTn8GWVgqOq/view?usp=sharing

**Comment by daniel86** [comment]
would it be possible to include such tests in travis CI?
That would be cool, I think

**Comment by mcodescu** [comment]
I'd say the reported issues are a matter of interpretation in many cases (you might have a reason not to add a domain axiom for a property) and should not be part of a mandatory test. Maybe one idea would be to require that no critical issues are reported. 

OOPS! is available as a RESTful service so it should be possible to write a script that runs the test on a given ontology and interprets the results.

**Comment by mpomarlan** [comment]
As long as we can suppress certain warnings. Not the warning type in general, but a particular warning, caused by a particular part of the ontology. A lot of the OOPS warnings are actually caused by DUL (ba-dum-tish).
