### ISSUE TITLE
The ontology can't be reasoned with

### ISSUE THREAD

**Issue by mpomarlan** [ease-crc/ease_ontology#35]
At least, not when using DL reasoners such as Pellet, Hermit, or basically anything else that Protege comes with.

Presumably some highly non-standard DL reasoner might handle it, or maybe a full fledged first-order theorem prover, but this somewhat defeats the purpose of having an ontology in OWL. It's supposed to be accessible to standard DL techniques.

The problem comes from temporal properties such as after, before, startedBy, finishedBy-- any combo of Transient, Asymmetric, Irreflexive is highly suspect, and if these occur in property chains as well then DL reasoners can't handle them.

Suggested fix: isolate the problem object properties into another module, on which hopefully we will almost never depend.

**Comment by porzel** [comment]
Sounds like as plan.

**Comment by mpomarlan** [comment]
Fixed by #37
