### ISSUE TITLE
Distinction Composite/Noncomposite Action and Activity

### ISSUE THREAD

**Issue by daniel86** [ease-crc/ease_ontology#4]
I think we were still unsure about this distinction.

- it seems to depend on level of granularity if an action is composite/non composite. As granularity might depend on in which EASE subgroup you are part of, it might be better to not make this distinction on the foundational level
- as `Activity` is part of the name EASE, we should also have an `Activity` concept

My(daniel's) proposal:
1. Drop terms composite/noncomposite as they are not intuitive
2. Define `Activity` as subclass of `Event`
3. Distinction between `Action` and `Activity`

Still, what are the criteria for being an action/activity? The distinction should sufficiently guide people modelling actions and activities.

**Comment by mpomarlan** [comment]
Action vs. Activities: let's try to figure out this one. Here's a candidate for the distinction: an activity is routine and/or scheduled; see the first answer in this quora thread: https://www.quora.com/What-is-the-difference-between-action-and-activity-in-English

**Comment by daniel86** [comment]
Thanks for providing new input @mpomarlan !
So here we have two new terms *routine* and *scheduled* which would need more explanation.

- What is a routine? And why aren't "simple actions" (e.g. reaching) routines? I guess at least it's something which happens regularly. But this is also the case for "simple actions" such as reaching.
- You could say our brain schedules all our motions, and also the "simple actions". Scheduled wrt. other actions and the overall goal during this situation could be more helpful, maybe?

Maybe we will need to distinguish between *high-level* and *low-level goals*? Then a/the distinction would be that activities are performed to achieve high-level goals while actions are performed to achieve lower-level goals. But this would move the problem of distinguishing to the terms low-level and high-level goal.
